// ac.getCarName
[
	'ks_ruf_rt12r',
	'abarth500',
	'abarth500_s1': '',
	'ks_alfa_romeo_155_v6',
	'ks_alfa_romeo_4c',
	'ks_alfa_romeo_gta',
	'ks_alfa_mito_qv',
	'alfa_romeo_giulietta_qv',
	'alfa_romeo_giulietta_qv_le',
	'ks_audi_r8_lms',
	'ks_audi_sport_quattro',
	'ks_audi_sport_quattro_s1',
	'bmw_1m',
	'bmw_1m_s3',
	'ks_bmw_m235i_racing',
	'bmw_m3_e30',
	'bmw_m3_e30_drift',
	'bmw_m3_e30_s1',
	'bmw_m3_e30_gra',
	'bmw_m3_e30_dtm',
	'bmw_m3_e92',
	'bmw_m3_e92_drift',
	'bmw_m3_e92_s1'
	bmw_m3_gt2,
	ks_bmw_m4,
	ks_bmw_m4_akrapovic,
	bmw_z4,
	bmw_z4_drift,
	bmw_z4_s1,
	bmw_z4_gt3,
	ks_corvette_c7r,
	ferrari_312t,
	ferrari_458_gt2,
	ferrari_458,
	ferrari_458_s3,
	ferrari_599xxevo,
	ferrari_f40,
	ferrari_f40_s3,
	ferrari_laferrari,
	ks_ford_gt40,
	ktm_xbow_r,
	ks_lamborghini_countach,
	ks_lamborghini_countach_s1,
	ks_lamborghini_huracan_gt3,
	ks_lamborghini_miura_sv,
	lotus_2_eleven,
	lotus_2_eleven_gt4,
	lotus_elise_sc,
	lotus_elise_sc_s1,
	lotus_elise_sc_s2,
	lotus_evora_gtc,
	lotus_evora_gte,
	lotus_evora_gte_carbon,
	lotus_evora_gx,
	lotus_evora_s,
	lotus_evora_s_s2,
	lotus_exige_240,
	lotus_exige_240_s3,
	lotus_exige_s,
	lotus_exige_s_roadster,
	lotus_exige_scura,
	lotus_exige_v6_cup,
	lotus_exos_125,
	lotus_exos_125_s1,
	lotus_98t,
	lotus_49,
	ks_mclaren_f1_gtr,
	mclaren_mp412c,
	mclaren_mp412c_gt3,
	ks_mclaren_p1,
	mercedes_sls,
	mercedes_sls_gt3,
	ks_mercedes_190_evo2,
	ks_mercedes_c9,
	ks_nissan_gtr_gt3,
	ks_nissan_gtr,
	pagani_huayra,
	pagani_zonda_r,
	ruf_yellowbird,
	ks_ruf_rt12r,
	ks_ruf_rt12r_awd,
	p4-5_2011,
	ks_glickenhaus_scg003,
	shelby_cobra_427sc,
	tatuusfa1,
	ks_toyota_gt86,
	// MODS
	audi_tt_cup_2015,
	caterham_academy,
	corvette_dp_c_hd,
	corvette_dp_d_hd,
	ford_sierra_cosworth_rs500,
	ford_sierra_cosworth_rs500_drift,
	ford_sierra_cosworth_rs500_dtm,
	ford_sierra_cosworth_rs500_gra,
	broadspeedjaguar_final1,
	mazda_787b,
	mazda_miata,
	vsf1_mclaren-mp413,
	oreca_flm09,
	ds3_wrc_2015,
	vsfr-formularenault35_2014_md,
	vsfr-formularenault35_2014_hdf,
	vsfr-formularenault35_2014_ldf,
	sareni_camaro_gt3,
	sareni_camaro_gt_racecar,
	sareni_camaro_gt_racecar,
	ifm_2009,
	ifm_2009_hc,
	shelby_cobra,
	shelby_cobra_s1,
	shelby_cobra_competition,
	dallara_f312,
	ferrari_288gto,
	ferrari_288gto_grb,
	vsf1_ferrari_concept,
	calibra_dtm,
	peugeot_504,
	corvette_c6r
]

// ac.getTrackName
[
	'silverstone-national',
	'silverstone',
	// For both GP and MOTO layout ##
	'ks_barcelona',
	'drift',
	'imola',
	'magione',
	'monza',
	'monza66',
	'mugello',
	// For nordschleife, endurance, touristenfahrten layout
	'ks_nordschleife',
	'nurburgring',
	'nurburgring-sprint',
	'silverstone-international',
	'spa',
	'trento-baondone',
	// For both extended_circuit and club_circuit
	'vallelunga',
	'ks_zandvoort',
	// MODS
	barbagallo,
	blackwood,
	bridgehampton,
	montreal,
	// For gp & national
	doningtonpark,
	gentrack1,
	grobnik,
	// for tarmac, tarmacdownhill
	krajiskazmija,
	luccaring,
	// for mills_long, 
	mills10,
	miseluk,
	// for blancpain, tourism_gt_24h, wtcc
	paul_ricard,
	salzburgring,
	// for circuit_south, circuit_full
	spielberg,
	// for race
	tor_poznan,
	holjesrx
]


// EMpty when no config for track
// ac.getTrackConfiguration
[
	// for ks_barcelona ##
	'layout_gp',
	'layout_moto',
	// for ks_nordschleife
	'nordschleife',
	'endurance',
	'touristenfahrten',
	// for vallelunga
	'extended_circuit',
	'club_circuit',
	// for doningtonpark
	gp,
	national,
	// for krajiskazmija
	tarmac,
	tarmacdownhill,
	// for mills10
	mills_long,
	mills_short,
	// for paul_ricard
	blancpain,
	tourism_gt_24h,
	wtcc,
	// for spielberg
	circuit_south,
	circuit_full,
	// for tor_poznan
	race
]
